name: test playbook

nodes:
  - hostname: localhost
    port: 8071

variables:
  - name: "v1"
  - name: "v3"
    value: "290"

vault:
  - key: "v2"

stages:
  - action: "Eval"
    display: "add 30 + 20 + 10 to variable v3"
    parameters:
      expression: "{{v3}} + {{ ind }} * 10"
      result: "v3"
    loop:
      index: "ind"
      range: 3
  - action: "Execute"
    display: "execute dir command if v3 == 350"
    condition: "{{v3}} == 350"
    parameters:
      command: "dir"
  - action: "Execute"
    display: "get pwd"
    parameters:
      command: "pwd"
      result: "v1"
  - action: "Debug"
    display: "display contents of variables"
    parameters:
      message: "{{item}}"
    foreach:
      items:
        - "v1 is {{v1}}"
        - "v2 is {{v2}}"
        - "v3 is {{v3}}"
  - action: "File"
    display: "create new directory"
    parameters:
      path: "{{v1}}/tst"
      state: directory
  - action: "Template"
    display: "generate a sample file to compress later"
    parameters:
      body: |
        this is a sample of an inline template
        which will of course have several lines
        that we can enter like this.
        ah by the way, this is the value of the
        v1 variable: {{v1}}
        and as you know already, this is the value
        of v3 variable: {{v3}}
        and we can continue like that for a long
        time... again, and again...
        and again.
        okay that's all folks!
      path: "{{v1}}/temp.txt"
  - action: "CopyFile"
    display: "copy the template to the test folder"
    parameters:
      from: "./temp.txt"
      to: "./tst/temp.txt"
  - action: "DownloadFile"
    display: "test download file from intranet"
    parameters:
      url: "https://i.redd.it/9sndjq3h2oz41.png"
      path: "./tst/ubuntu-logo.png"
  - action: "Zip"
    display: "compress protoc plugins folder"
    parameters:
      path: "./grpc-agent/target/protoc-plugins"
      archive: "./plugins.zip"
  - action: "Unzip"
    display: "decompress plugins.zip to tst folder"
    parameters:
      archive: "./plugins.zip"
      destination: "./tst"
  - action: "Execute"
    display: "show files"
    parameters:
      command: "dir tst"
  - action: "File"
    display: "delete test archive"
    parameters:
      path: "./plugins.zip"
      state: "absent"
  - action: "Archive"
    display: "create tar.gz from test folder"
    parameters:
      directory: "./tst"
      path: "./test.tar.gz"
      action: "compress"
  - action: "File"
    display: "delete test directory"
    parameters:
      path: "./tst"
      state: "absent"
  - action: "File"
    display: "delete test template"
    parameters:
      path: "./temp.txt"
      state: "absent"
  - action: "Execute"
    display: "show files"
    parameters:
      command: "dir"
  - action: "Archive"
    display: "untar to the new test folder"
    parameters:
      directory: "./newtest"
      path: "./test.tar.gz"
      action: "uncompress"
  - action: "File"
    display: "delete tar.gz archive"
    parameters:
      path: "./test.tar.gz"
      state: "absent"
  - action: "Execute"
    display: "show files"
    parameters:
      command: "dir newtest"
  - action: "Lines"
    display: "add a new line to temp.txt"
    parameters:
      file: "./newtest/tst/temp.txt"
      regexp: "and as you know already"
      before: "nice, isn't it?"
  - action: "Lines"
    display: "add another line to temp.txt"
    parameters:
      file: "./newtest/tst/temp.txt"
      regexp: "enter.+this"
      after: "this is another line."
  - action: "Lines"
    display: "and replace again by never"
    parameters:
      file: "./newtest/tst/temp.txt"
      regexp: "again"
      replace: "never"
  - action: "Debug"
    display: "show content of test file"
    parameters:
      file: "./newtest/tst/temp.txt"
  - action: "File"
    display: "remove newtest folder"
    parameters:
      path: "./newtest"
      state: "absent"
  - action: "Execute"
    display: "show files"
    parameters:
      command: "dir"