// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

/**
 * Protobuf type {@code agent.MForEach}
 */
public  final class MForEach extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.MForEach)
    MForEachOrBuilder {
  // Use MForEach.newBuilder() to construct.
  private MForEach(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MForEach() {
    items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MForEach(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              items_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = items_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MForEach_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MForEach_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.francoiscolombo.tools.automaton.grpc.agent.MForEach.class, net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder.class);
  }

  public static final int ITEMS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList items_;
  /**
   * <code>repeated string items = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getItemsList() {
    return items_;
  }
  /**
   * <code>repeated string items = 1;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated string items = 1;</code>
   */
  public java.lang.String getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated string items = 1;</code>
   */
  public com.google.protobuf.ByteString
      getItemsBytes(int index) {
    return items_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, items_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < items_.size(); i++) {
        dataSize += computeStringSizeNoTag(items_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getItemsList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.francoiscolombo.tools.automaton.grpc.agent.MForEach)) {
      return super.equals(obj);
    }
    net.francoiscolombo.tools.automaton.grpc.agent.MForEach other = (net.francoiscolombo.tools.automaton.grpc.agent.MForEach) obj;

    boolean result = true;
    result = result && getItemsList()
        .equals(other.getItemsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.francoiscolombo.tools.automaton.grpc.agent.MForEach prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.MForEach}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.MForEach)
      net.francoiscolombo.tools.automaton.grpc.agent.MForEachOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MForEach_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MForEach_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.francoiscolombo.tools.automaton.grpc.agent.MForEach.class, net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder.class);
    }

    // Construct using net.francoiscolombo.tools.automaton.grpc.agent.MForEach.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MForEach_descriptor;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MForEach getDefaultInstanceForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.MForEach.getDefaultInstance();
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MForEach build() {
      net.francoiscolombo.tools.automaton.grpc.agent.MForEach result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MForEach buildPartial() {
      net.francoiscolombo.tools.automaton.grpc.agent.MForEach result = new net.francoiscolombo.tools.automaton.grpc.agent.MForEach(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = items_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.items_ = items_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.francoiscolombo.tools.automaton.grpc.agent.MForEach) {
        return mergeFrom((net.francoiscolombo.tools.automaton.grpc.agent.MForEach)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.francoiscolombo.tools.automaton.grpc.agent.MForEach other) {
      if (other == net.francoiscolombo.tools.automaton.grpc.agent.MForEach.getDefaultInstance()) return this;
      if (!other.items_.isEmpty()) {
        if (items_.isEmpty()) {
          items_ = other.items_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureItemsIsMutable();
          items_.addAll(other.items_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.francoiscolombo.tools.automaton.grpc.agent.MForEach parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.francoiscolombo.tools.automaton.grpc.agent.MForEach) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = new com.google.protobuf.LazyStringArrayList(items_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getItemsList() {
      return items_.getUnmodifiableView();
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public java.lang.String getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemsBytes(int index) {
      return items_.getByteString(index);
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public Builder setItems(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureItemsIsMutable();
      items_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public Builder addItems(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureItemsIsMutable();
      items_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<java.lang.String> values) {
      ensureItemsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, items_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public Builder clearItems() {
      items_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string items = 1;</code>
     */
    public Builder addItemsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureItemsIsMutable();
      items_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:agent.MForEach)
  }

  // @@protoc_insertion_point(class_scope:agent.MForEach)
  private static final net.francoiscolombo.tools.automaton.grpc.agent.MForEach DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.francoiscolombo.tools.automaton.grpc.agent.MForEach();
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MForEach getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MForEach>
      PARSER = new com.google.protobuf.AbstractParser<MForEach>() {
    public MForEach parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MForEach(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MForEach> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MForEach> getParserForType() {
    return PARSER;
  }

  public net.francoiscolombo.tools.automaton.grpc.agent.MForEach getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

