// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MForEachOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MForEach)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string items = 1;</code>
   */
  java.util.List<java.lang.String>
      getItemsList();
  /**
   * <code>repeated string items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated string items = 1;</code>
   */
  java.lang.String getItems(int index);
  /**
   * <code>repeated string items = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemsBytes(int index);
}
