// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MLoopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MLoop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string index = 1;</code>
   */
  java.lang.String getIndex();
  /**
   * <code>string index = 1;</code>
   */
  com.google.protobuf.ByteString
      getIndexBytes();

  /**
   * <code>uint32 range = 2;</code>
   */
  int getRange();
}
