// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

/**
 * Protobuf type {@code agent.MLoop}
 */
public  final class MLoop extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.MLoop)
    MLoopOrBuilder {
  // Use MLoop.newBuilder() to construct.
  private MLoop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MLoop() {
    index_ = "";
    range_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MLoop(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            index_ = s;
            break;
          }
          case 16: {

            range_ = input.readUInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MLoop_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MLoop_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.francoiscolombo.tools.automaton.grpc.agent.MLoop.class, net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder.class);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private volatile java.lang.Object index_;
  /**
   * <code>string index = 1;</code>
   */
  public java.lang.String getIndex() {
    java.lang.Object ref = index_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      index_ = s;
      return s;
    }
  }
  /**
   * <code>string index = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIndexBytes() {
    java.lang.Object ref = index_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      index_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RANGE_FIELD_NUMBER = 2;
  private int range_;
  /**
   * <code>uint32 range = 2;</code>
   */
  public int getRange() {
    return range_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIndexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, index_);
    }
    if (range_ != 0) {
      output.writeUInt32(2, range_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIndexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, index_);
    }
    if (range_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, range_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.francoiscolombo.tools.automaton.grpc.agent.MLoop)) {
      return super.equals(obj);
    }
    net.francoiscolombo.tools.automaton.grpc.agent.MLoop other = (net.francoiscolombo.tools.automaton.grpc.agent.MLoop) obj;

    boolean result = true;
    result = result && getIndex()
        .equals(other.getIndex());
    result = result && (getRange()
        == other.getRange());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex().hashCode();
    hash = (37 * hash) + RANGE_FIELD_NUMBER;
    hash = (53 * hash) + getRange();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.francoiscolombo.tools.automaton.grpc.agent.MLoop prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.MLoop}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.MLoop)
      net.francoiscolombo.tools.automaton.grpc.agent.MLoopOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MLoop_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MLoop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.francoiscolombo.tools.automaton.grpc.agent.MLoop.class, net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder.class);
    }

    // Construct using net.francoiscolombo.tools.automaton.grpc.agent.MLoop.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      index_ = "";

      range_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MLoop_descriptor;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MLoop getDefaultInstanceForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.MLoop.getDefaultInstance();
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MLoop build() {
      net.francoiscolombo.tools.automaton.grpc.agent.MLoop result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MLoop buildPartial() {
      net.francoiscolombo.tools.automaton.grpc.agent.MLoop result = new net.francoiscolombo.tools.automaton.grpc.agent.MLoop(this);
      result.index_ = index_;
      result.range_ = range_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.francoiscolombo.tools.automaton.grpc.agent.MLoop) {
        return mergeFrom((net.francoiscolombo.tools.automaton.grpc.agent.MLoop)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.francoiscolombo.tools.automaton.grpc.agent.MLoop other) {
      if (other == net.francoiscolombo.tools.automaton.grpc.agent.MLoop.getDefaultInstance()) return this;
      if (!other.getIndex().isEmpty()) {
        index_ = other.index_;
        onChanged();
      }
      if (other.getRange() != 0) {
        setRange(other.getRange());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.francoiscolombo.tools.automaton.grpc.agent.MLoop parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.francoiscolombo.tools.automaton.grpc.agent.MLoop) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object index_ = "";
    /**
     * <code>string index = 1;</code>
     */
    public java.lang.String getIndex() {
      java.lang.Object ref = index_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        index_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string index = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIndexBytes() {
      java.lang.Object ref = index_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        index_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder setIndex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder clearIndex() {
      
      index_ = getDefaultInstance().getIndex();
      onChanged();
      return this;
    }
    /**
     * <code>string index = 1;</code>
     */
    public Builder setIndexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      index_ = value;
      onChanged();
      return this;
    }

    private int range_ ;
    /**
     * <code>uint32 range = 2;</code>
     */
    public int getRange() {
      return range_;
    }
    /**
     * <code>uint32 range = 2;</code>
     */
    public Builder setRange(int value) {
      
      range_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 range = 2;</code>
     */
    public Builder clearRange() {
      
      range_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:agent.MLoop)
  }

  // @@protoc_insertion_point(class_scope:agent.MLoop)
  private static final net.francoiscolombo.tools.automaton.grpc.agent.MLoop DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.francoiscolombo.tools.automaton.grpc.agent.MLoop();
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MLoop getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MLoop>
      PARSER = new com.google.protobuf.AbstractParser<MLoop>() {
    public MLoop parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MLoop(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MLoop> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MLoop> getParserForType() {
    return PARSER;
  }

  public net.francoiscolombo.tools.automaton.grpc.agent.MLoop getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

