// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pname = 1;</code>
   */
  java.lang.String getPname();
  /**
   * <code>string pname = 1;</code>
   */
  com.google.protobuf.ByteString
      getPnameBytes();

  /**
   * <code>string pvalue = 2;</code>
   */
  java.lang.String getPvalue();
  /**
   * <code>string pvalue = 2;</code>
   */
  com.google.protobuf.ByteString
      getPvalueBytes();
}
