// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MPingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MPing)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ping = 1;</code>
   */
  java.lang.String getPing();
  /**
   * <code>string ping = 1;</code>
   */
  com.google.protobuf.ByteString
      getPingBytes();
}
