// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MPlaybookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MPlaybook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MVariable> 
      getVariablesList();
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MVariable getVariables(int index);
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  int getVariablesCount();
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder> 
      getVariablesOrBuilderList();
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder getVariablesOrBuilder(
      int index);

  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MStage> 
      getStagesList();
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MStage getStages(int index);
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  int getStagesCount();
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder> 
      getStagesOrBuilderList();
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder getStagesOrBuilder(
      int index);
}
