// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

/**
 * Protobuf type {@code agent.MPlaybook}
 */
public  final class MPlaybook extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.MPlaybook)
    MPlaybookOrBuilder {
  // Use MPlaybook.newBuilder() to construct.
  private MPlaybook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MPlaybook() {
    name_ = "";
    variables_ = java.util.Collections.emptyList();
    stages_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MPlaybook(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              variables_ = new java.util.ArrayList<net.francoiscolombo.tools.automaton.grpc.agent.MVariable>();
              mutable_bitField0_ |= 0x00000002;
            }
            variables_.add(
                input.readMessage(net.francoiscolombo.tools.automaton.grpc.agent.MVariable.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              stages_ = new java.util.ArrayList<net.francoiscolombo.tools.automaton.grpc.agent.MStage>();
              mutable_bitField0_ |= 0x00000004;
            }
            stages_.add(
                input.readMessage(net.francoiscolombo.tools.automaton.grpc.agent.MStage.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        variables_ = java.util.Collections.unmodifiableList(variables_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        stages_ = java.util.Collections.unmodifiableList(stages_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPlaybook_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPlaybook_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook.class, net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARIABLES_FIELD_NUMBER = 2;
  private java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MVariable> variables_;
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MVariable> getVariablesList() {
    return variables_;
  }
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  public java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder> 
      getVariablesOrBuilderList() {
    return variables_;
  }
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  public int getVariablesCount() {
    return variables_.size();
  }
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MVariable getVariables(int index) {
    return variables_.get(index);
  }
  /**
   * <code>repeated .agent.MVariable variables = 2;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder getVariablesOrBuilder(
      int index) {
    return variables_.get(index);
  }

  public static final int STAGES_FIELD_NUMBER = 3;
  private java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MStage> stages_;
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MStage> getStagesList() {
    return stages_;
  }
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  public java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder> 
      getStagesOrBuilderList() {
    return stages_;
  }
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  public int getStagesCount() {
    return stages_.size();
  }
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MStage getStages(int index) {
    return stages_.get(index);
  }
  /**
   * <code>repeated .agent.MStage stages = 3;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder getStagesOrBuilder(
      int index) {
    return stages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < variables_.size(); i++) {
      output.writeMessage(2, variables_.get(i));
    }
    for (int i = 0; i < stages_.size(); i++) {
      output.writeMessage(3, stages_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < variables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, variables_.get(i));
    }
    for (int i = 0; i < stages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, stages_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook)) {
      return super.equals(obj);
    }
    net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook other = (net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getVariablesList()
        .equals(other.getVariablesList());
    result = result && getStagesList()
        .equals(other.getStagesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getVariablesCount() > 0) {
      hash = (37 * hash) + VARIABLES_FIELD_NUMBER;
      hash = (53 * hash) + getVariablesList().hashCode();
    }
    if (getStagesCount() > 0) {
      hash = (37 * hash) + STAGES_FIELD_NUMBER;
      hash = (53 * hash) + getStagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.MPlaybook}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.MPlaybook)
      net.francoiscolombo.tools.automaton.grpc.agent.MPlaybookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPlaybook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPlaybook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook.class, net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook.Builder.class);
    }

    // Construct using net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVariablesFieldBuilder();
        getStagesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      if (variablesBuilder_ == null) {
        variables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        variablesBuilder_.clear();
      }
      if (stagesBuilder_ == null) {
        stages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        stagesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPlaybook_descriptor;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook getDefaultInstanceForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook.getDefaultInstance();
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook build() {
      net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook buildPartial() {
      net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook result = new net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      if (variablesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          variables_ = java.util.Collections.unmodifiableList(variables_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.variables_ = variables_;
      } else {
        result.variables_ = variablesBuilder_.build();
      }
      if (stagesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stages_ = java.util.Collections.unmodifiableList(stages_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stages_ = stages_;
      } else {
        result.stages_ = stagesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook) {
        return mergeFrom((net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook other) {
      if (other == net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (variablesBuilder_ == null) {
        if (!other.variables_.isEmpty()) {
          if (variables_.isEmpty()) {
            variables_ = other.variables_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureVariablesIsMutable();
            variables_.addAll(other.variables_);
          }
          onChanged();
        }
      } else {
        if (!other.variables_.isEmpty()) {
          if (variablesBuilder_.isEmpty()) {
            variablesBuilder_.dispose();
            variablesBuilder_ = null;
            variables_ = other.variables_;
            bitField0_ = (bitField0_ & ~0x00000002);
            variablesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariablesFieldBuilder() : null;
          } else {
            variablesBuilder_.addAllMessages(other.variables_);
          }
        }
      }
      if (stagesBuilder_ == null) {
        if (!other.stages_.isEmpty()) {
          if (stages_.isEmpty()) {
            stages_ = other.stages_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStagesIsMutable();
            stages_.addAll(other.stages_);
          }
          onChanged();
        }
      } else {
        if (!other.stages_.isEmpty()) {
          if (stagesBuilder_.isEmpty()) {
            stagesBuilder_.dispose();
            stagesBuilder_ = null;
            stages_ = other.stages_;
            bitField0_ = (bitField0_ & ~0x00000004);
            stagesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStagesFieldBuilder() : null;
          } else {
            stagesBuilder_.addAllMessages(other.stages_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MVariable> variables_ =
      java.util.Collections.emptyList();
    private void ensureVariablesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        variables_ = new java.util.ArrayList<net.francoiscolombo.tools.automaton.grpc.agent.MVariable>(variables_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MVariable, net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder> variablesBuilder_;

    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MVariable> getVariablesList() {
      if (variablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variables_);
      } else {
        return variablesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public int getVariablesCount() {
      if (variablesBuilder_ == null) {
        return variables_.size();
      } else {
        return variablesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MVariable getVariables(int index) {
      if (variablesBuilder_ == null) {
        return variables_.get(index);
      } else {
        return variablesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder setVariables(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MVariable value) {
      if (variablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariablesIsMutable();
        variables_.set(index, value);
        onChanged();
      } else {
        variablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder setVariables(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder builderForValue) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.set(index, builderForValue.build());
        onChanged();
      } else {
        variablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder addVariables(net.francoiscolombo.tools.automaton.grpc.agent.MVariable value) {
      if (variablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariablesIsMutable();
        variables_.add(value);
        onChanged();
      } else {
        variablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder addVariables(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MVariable value) {
      if (variablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariablesIsMutable();
        variables_.add(index, value);
        onChanged();
      } else {
        variablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder addVariables(
        net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder builderForValue) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.add(builderForValue.build());
        onChanged();
      } else {
        variablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder addVariables(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder builderForValue) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.add(index, builderForValue.build());
        onChanged();
      } else {
        variablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder addAllVariables(
        java.lang.Iterable<? extends net.francoiscolombo.tools.automaton.grpc.agent.MVariable> values) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variables_);
        onChanged();
      } else {
        variablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder clearVariables() {
      if (variablesBuilder_ == null) {
        variables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        variablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public Builder removeVariables(int index) {
      if (variablesBuilder_ == null) {
        ensureVariablesIsMutable();
        variables_.remove(index);
        onChanged();
      } else {
        variablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder getVariablesBuilder(
        int index) {
      return getVariablesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder getVariablesOrBuilder(
        int index) {
      if (variablesBuilder_ == null) {
        return variables_.get(index);  } else {
        return variablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder> 
         getVariablesOrBuilderList() {
      if (variablesBuilder_ != null) {
        return variablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variables_);
      }
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder addVariablesBuilder() {
      return getVariablesFieldBuilder().addBuilder(
          net.francoiscolombo.tools.automaton.grpc.agent.MVariable.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder addVariablesBuilder(
        int index) {
      return getVariablesFieldBuilder().addBuilder(
          index, net.francoiscolombo.tools.automaton.grpc.agent.MVariable.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.MVariable variables = 2;</code>
     */
    public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder> 
         getVariablesBuilderList() {
      return getVariablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MVariable, net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder> 
        getVariablesFieldBuilder() {
      if (variablesBuilder_ == null) {
        variablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.francoiscolombo.tools.automaton.grpc.agent.MVariable, net.francoiscolombo.tools.automaton.grpc.agent.MVariable.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MVariableOrBuilder>(
                variables_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        variables_ = null;
      }
      return variablesBuilder_;
    }

    private java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MStage> stages_ =
      java.util.Collections.emptyList();
    private void ensureStagesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        stages_ = new java.util.ArrayList<net.francoiscolombo.tools.automaton.grpc.agent.MStage>(stages_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MStage, net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder> stagesBuilder_;

    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MStage> getStagesList() {
      if (stagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stages_);
      } else {
        return stagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public int getStagesCount() {
      if (stagesBuilder_ == null) {
        return stages_.size();
      } else {
        return stagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MStage getStages(int index) {
      if (stagesBuilder_ == null) {
        return stages_.get(index);
      } else {
        return stagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder setStages(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MStage value) {
      if (stagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStagesIsMutable();
        stages_.set(index, value);
        onChanged();
      } else {
        stagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder setStages(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder builderForValue) {
      if (stagesBuilder_ == null) {
        ensureStagesIsMutable();
        stages_.set(index, builderForValue.build());
        onChanged();
      } else {
        stagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder addStages(net.francoiscolombo.tools.automaton.grpc.agent.MStage value) {
      if (stagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStagesIsMutable();
        stages_.add(value);
        onChanged();
      } else {
        stagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder addStages(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MStage value) {
      if (stagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStagesIsMutable();
        stages_.add(index, value);
        onChanged();
      } else {
        stagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder addStages(
        net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder builderForValue) {
      if (stagesBuilder_ == null) {
        ensureStagesIsMutable();
        stages_.add(builderForValue.build());
        onChanged();
      } else {
        stagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder addStages(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder builderForValue) {
      if (stagesBuilder_ == null) {
        ensureStagesIsMutable();
        stages_.add(index, builderForValue.build());
        onChanged();
      } else {
        stagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder addAllStages(
        java.lang.Iterable<? extends net.francoiscolombo.tools.automaton.grpc.agent.MStage> values) {
      if (stagesBuilder_ == null) {
        ensureStagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stages_);
        onChanged();
      } else {
        stagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder clearStages() {
      if (stagesBuilder_ == null) {
        stages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        stagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public Builder removeStages(int index) {
      if (stagesBuilder_ == null) {
        ensureStagesIsMutable();
        stages_.remove(index);
        onChanged();
      } else {
        stagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder getStagesBuilder(
        int index) {
      return getStagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder getStagesOrBuilder(
        int index) {
      if (stagesBuilder_ == null) {
        return stages_.get(index);  } else {
        return stagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder> 
         getStagesOrBuilderList() {
      if (stagesBuilder_ != null) {
        return stagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stages_);
      }
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder addStagesBuilder() {
      return getStagesFieldBuilder().addBuilder(
          net.francoiscolombo.tools.automaton.grpc.agent.MStage.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder addStagesBuilder(
        int index) {
      return getStagesFieldBuilder().addBuilder(
          index, net.francoiscolombo.tools.automaton.grpc.agent.MStage.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.MStage stages = 3;</code>
     */
    public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder> 
         getStagesBuilderList() {
      return getStagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MStage, net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder> 
        getStagesFieldBuilder() {
      if (stagesBuilder_ == null) {
        stagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.francoiscolombo.tools.automaton.grpc.agent.MStage, net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder>(
                stages_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        stages_ = null;
      }
      return stagesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:agent.MPlaybook)
  }

  // @@protoc_insertion_point(class_scope:agent.MPlaybook)
  private static final net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook();
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MPlaybook>
      PARSER = new com.google.protobuf.AbstractParser<MPlaybook>() {
    public MPlaybook parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MPlaybook(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MPlaybook> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MPlaybook> getParserForType() {
    return PARSER;
  }

  public net.francoiscolombo.tools.automaton.grpc.agent.MPlaybook getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

