// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MPongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MPong)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pong = 1;</code>
   */
  java.lang.String getPong();
  /**
   * <code>string pong = 1;</code>
   */
  com.google.protobuf.ByteString
      getPongBytes();
}
