// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

/**
 * Protobuf type {@code agent.MPong}
 */
public  final class MPong extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.MPong)
    MPongOrBuilder {
  // Use MPong.newBuilder() to construct.
  private MPong(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MPong() {
    pong_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MPong(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            pong_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPong_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPong_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.francoiscolombo.tools.automaton.grpc.agent.MPong.class, net.francoiscolombo.tools.automaton.grpc.agent.MPong.Builder.class);
  }

  public static final int PONG_FIELD_NUMBER = 1;
  private volatile java.lang.Object pong_;
  /**
   * <code>string pong = 1;</code>
   */
  public java.lang.String getPong() {
    java.lang.Object ref = pong_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pong_ = s;
      return s;
    }
  }
  /**
   * <code>string pong = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPongBytes() {
    java.lang.Object ref = pong_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pong_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPongBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pong_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPongBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pong_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.francoiscolombo.tools.automaton.grpc.agent.MPong)) {
      return super.equals(obj);
    }
    net.francoiscolombo.tools.automaton.grpc.agent.MPong other = (net.francoiscolombo.tools.automaton.grpc.agent.MPong) obj;

    boolean result = true;
    result = result && getPong()
        .equals(other.getPong());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PONG_FIELD_NUMBER;
    hash = (53 * hash) + getPong().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.francoiscolombo.tools.automaton.grpc.agent.MPong prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.MPong}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.MPong)
      net.francoiscolombo.tools.automaton.grpc.agent.MPongOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPong_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.francoiscolombo.tools.automaton.grpc.agent.MPong.class, net.francoiscolombo.tools.automaton.grpc.agent.MPong.Builder.class);
    }

    // Construct using net.francoiscolombo.tools.automaton.grpc.agent.MPong.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      pong_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MPong_descriptor;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MPong getDefaultInstanceForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.MPong.getDefaultInstance();
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MPong build() {
      net.francoiscolombo.tools.automaton.grpc.agent.MPong result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MPong buildPartial() {
      net.francoiscolombo.tools.automaton.grpc.agent.MPong result = new net.francoiscolombo.tools.automaton.grpc.agent.MPong(this);
      result.pong_ = pong_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.francoiscolombo.tools.automaton.grpc.agent.MPong) {
        return mergeFrom((net.francoiscolombo.tools.automaton.grpc.agent.MPong)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.francoiscolombo.tools.automaton.grpc.agent.MPong other) {
      if (other == net.francoiscolombo.tools.automaton.grpc.agent.MPong.getDefaultInstance()) return this;
      if (!other.getPong().isEmpty()) {
        pong_ = other.pong_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.francoiscolombo.tools.automaton.grpc.agent.MPong parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.francoiscolombo.tools.automaton.grpc.agent.MPong) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object pong_ = "";
    /**
     * <code>string pong = 1;</code>
     */
    public java.lang.String getPong() {
      java.lang.Object ref = pong_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pong_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pong = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPongBytes() {
      java.lang.Object ref = pong_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pong_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pong = 1;</code>
     */
    public Builder setPong(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pong_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pong = 1;</code>
     */
    public Builder clearPong() {
      
      pong_ = getDefaultInstance().getPong();
      onChanged();
      return this;
    }
    /**
     * <code>string pong = 1;</code>
     */
    public Builder setPongBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pong_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:agent.MPong)
  }

  // @@protoc_insertion_point(class_scope:agent.MPong)
  private static final net.francoiscolombo.tools.automaton.grpc.agent.MPong DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.francoiscolombo.tools.automaton.grpc.agent.MPong();
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MPong getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MPong>
      PARSER = new com.google.protobuf.AbstractParser<MPong>() {
    public MPong parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MPong(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MPong> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MPong> getParserForType() {
    return PARSER;
  }

  public net.francoiscolombo.tools.automaton.grpc.agent.MPong getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

