// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string reason = 2;</code>
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
