// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MSendFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MSendFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string path = 2;</code>
   */
  java.lang.String getPath();
  /**
   * <code>string path = 2;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int64 offset = 4;</code>
   */
  long getOffset();
}
