// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public interface MStageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.MStage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string action = 1;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 1;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string display = 2;</code>
   */
  java.lang.String getDisplay();
  /**
   * <code>string display = 2;</code>
   */
  com.google.protobuf.ByteString
      getDisplayBytes();

  /**
   * <code>string condition = 3;</code>
   */
  java.lang.String getCondition();
  /**
   * <code>string condition = 3;</code>
   */
  com.google.protobuf.ByteString
      getConditionBytes();

  /**
   * <code>.agent.MLoop loop = 4;</code>
   */
  boolean hasLoop();
  /**
   * <code>.agent.MLoop loop = 4;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MLoop getLoop();
  /**
   * <code>.agent.MLoop loop = 4;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MLoopOrBuilder getLoopOrBuilder();

  /**
   * <code>.agent.MForEach foreach = 5;</code>
   */
  boolean hasForeach();
  /**
   * <code>.agent.MForEach foreach = 5;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MForEach getForeach();
  /**
   * <code>.agent.MForEach foreach = 5;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MForEachOrBuilder getForeachOrBuilder();

  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MParameter> 
      getParametersList();
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MParameter getParameters(int index);
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder> 
      getParametersOrBuilderList();
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder getParametersOrBuilder(
      int index);
}
