// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

/**
 * Protobuf type {@code agent.MStage}
 */
public  final class MStage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:agent.MStage)
    MStageOrBuilder {
  // Use MStage.newBuilder() to construct.
  private MStage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MStage() {
    action_ = "";
    display_ = "";
    condition_ = "";
    parameters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private MStage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            display_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            condition_ = s;
            break;
          }
          case 34: {
            net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder subBuilder = null;
            if (loop_ != null) {
              subBuilder = loop_.toBuilder();
            }
            loop_ = input.readMessage(net.francoiscolombo.tools.automaton.grpc.agent.MLoop.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(loop_);
              loop_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder subBuilder = null;
            if (foreach_ != null) {
              subBuilder = foreach_.toBuilder();
            }
            foreach_ = input.readMessage(net.francoiscolombo.tools.automaton.grpc.agent.MForEach.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(foreach_);
              foreach_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              parameters_ = new java.util.ArrayList<net.francoiscolombo.tools.automaton.grpc.agent.MParameter>();
              mutable_bitField0_ |= 0x00000020;
            }
            parameters_.add(
                input.readMessage(net.francoiscolombo.tools.automaton.grpc.agent.MParameter.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        parameters_ = java.util.Collections.unmodifiableList(parameters_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MStage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MStage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.francoiscolombo.tools.automaton.grpc.agent.MStage.class, net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder.class);
  }

  private int bitField0_;
  public static final int ACTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object action_;
  /**
   * <code>string action = 1;</code>
   */
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string action = 1;</code>
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_FIELD_NUMBER = 2;
  private volatile java.lang.Object display_;
  /**
   * <code>string display = 2;</code>
   */
  public java.lang.String getDisplay() {
    java.lang.Object ref = display_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      display_ = s;
      return s;
    }
  }
  /**
   * <code>string display = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDisplayBytes() {
    java.lang.Object ref = display_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      display_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONDITION_FIELD_NUMBER = 3;
  private volatile java.lang.Object condition_;
  /**
   * <code>string condition = 3;</code>
   */
  public java.lang.String getCondition() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      condition_ = s;
      return s;
    }
  }
  /**
   * <code>string condition = 3;</code>
   */
  public com.google.protobuf.ByteString
      getConditionBytes() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      condition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOOP_FIELD_NUMBER = 4;
  private net.francoiscolombo.tools.automaton.grpc.agent.MLoop loop_;
  /**
   * <code>.agent.MLoop loop = 4;</code>
   */
  public boolean hasLoop() {
    return loop_ != null;
  }
  /**
   * <code>.agent.MLoop loop = 4;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MLoop getLoop() {
    return loop_ == null ? net.francoiscolombo.tools.automaton.grpc.agent.MLoop.getDefaultInstance() : loop_;
  }
  /**
   * <code>.agent.MLoop loop = 4;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MLoopOrBuilder getLoopOrBuilder() {
    return getLoop();
  }

  public static final int FOREACH_FIELD_NUMBER = 5;
  private net.francoiscolombo.tools.automaton.grpc.agent.MForEach foreach_;
  /**
   * <code>.agent.MForEach foreach = 5;</code>
   */
  public boolean hasForeach() {
    return foreach_ != null;
  }
  /**
   * <code>.agent.MForEach foreach = 5;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MForEach getForeach() {
    return foreach_ == null ? net.francoiscolombo.tools.automaton.grpc.agent.MForEach.getDefaultInstance() : foreach_;
  }
  /**
   * <code>.agent.MForEach foreach = 5;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MForEachOrBuilder getForeachOrBuilder() {
    return getForeach();
  }

  public static final int PARAMETERS_FIELD_NUMBER = 6;
  private java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MParameter> parameters_;
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MParameter> getParametersList() {
    return parameters_;
  }
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  public java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder> 
      getParametersOrBuilderList() {
    return parameters_;
  }
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  public int getParametersCount() {
    return parameters_.size();
  }
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MParameter getParameters(int index) {
    return parameters_.get(index);
  }
  /**
   * <code>repeated .agent.MParameter parameters = 6;</code>
   */
  public net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder getParametersOrBuilder(
      int index) {
    return parameters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
    }
    if (!getDisplayBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, display_);
    }
    if (!getConditionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, condition_);
    }
    if (loop_ != null) {
      output.writeMessage(4, getLoop());
    }
    if (foreach_ != null) {
      output.writeMessage(5, getForeach());
    }
    for (int i = 0; i < parameters_.size(); i++) {
      output.writeMessage(6, parameters_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
    }
    if (!getDisplayBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, display_);
    }
    if (!getConditionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, condition_);
    }
    if (loop_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLoop());
    }
    if (foreach_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getForeach());
    }
    for (int i = 0; i < parameters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, parameters_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.francoiscolombo.tools.automaton.grpc.agent.MStage)) {
      return super.equals(obj);
    }
    net.francoiscolombo.tools.automaton.grpc.agent.MStage other = (net.francoiscolombo.tools.automaton.grpc.agent.MStage) obj;

    boolean result = true;
    result = result && getAction()
        .equals(other.getAction());
    result = result && getDisplay()
        .equals(other.getDisplay());
    result = result && getCondition()
        .equals(other.getCondition());
    result = result && (hasLoop() == other.hasLoop());
    if (hasLoop()) {
      result = result && getLoop()
          .equals(other.getLoop());
    }
    result = result && (hasForeach() == other.hasForeach());
    if (hasForeach()) {
      result = result && getForeach()
          .equals(other.getForeach());
    }
    result = result && getParametersList()
        .equals(other.getParametersList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + DISPLAY_FIELD_NUMBER;
    hash = (53 * hash) + getDisplay().hashCode();
    hash = (37 * hash) + CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getCondition().hashCode();
    if (hasLoop()) {
      hash = (37 * hash) + LOOP_FIELD_NUMBER;
      hash = (53 * hash) + getLoop().hashCode();
    }
    if (hasForeach()) {
      hash = (37 * hash) + FOREACH_FIELD_NUMBER;
      hash = (53 * hash) + getForeach().hashCode();
    }
    if (getParametersCount() > 0) {
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParametersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.francoiscolombo.tools.automaton.grpc.agent.MStage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.MStage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.MStage)
      net.francoiscolombo.tools.automaton.grpc.agent.MStageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MStage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MStage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.francoiscolombo.tools.automaton.grpc.agent.MStage.class, net.francoiscolombo.tools.automaton.grpc.agent.MStage.Builder.class);
    }

    // Construct using net.francoiscolombo.tools.automaton.grpc.agent.MStage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getParametersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      action_ = "";

      display_ = "";

      condition_ = "";

      if (loopBuilder_ == null) {
        loop_ = null;
      } else {
        loop_ = null;
        loopBuilder_ = null;
      }
      if (foreachBuilder_ == null) {
        foreach_ = null;
      } else {
        foreach_ = null;
        foreachBuilder_ = null;
      }
      if (parametersBuilder_ == null) {
        parameters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        parametersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.Service.internal_static_agent_MStage_descriptor;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MStage getDefaultInstanceForType() {
      return net.francoiscolombo.tools.automaton.grpc.agent.MStage.getDefaultInstance();
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MStage build() {
      net.francoiscolombo.tools.automaton.grpc.agent.MStage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public net.francoiscolombo.tools.automaton.grpc.agent.MStage buildPartial() {
      net.francoiscolombo.tools.automaton.grpc.agent.MStage result = new net.francoiscolombo.tools.automaton.grpc.agent.MStage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.action_ = action_;
      result.display_ = display_;
      result.condition_ = condition_;
      if (loopBuilder_ == null) {
        result.loop_ = loop_;
      } else {
        result.loop_ = loopBuilder_.build();
      }
      if (foreachBuilder_ == null) {
        result.foreach_ = foreach_;
      } else {
        result.foreach_ = foreachBuilder_.build();
      }
      if (parametersBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          parameters_ = java.util.Collections.unmodifiableList(parameters_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.parameters_ = parameters_;
      } else {
        result.parameters_ = parametersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.francoiscolombo.tools.automaton.grpc.agent.MStage) {
        return mergeFrom((net.francoiscolombo.tools.automaton.grpc.agent.MStage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.francoiscolombo.tools.automaton.grpc.agent.MStage other) {
      if (other == net.francoiscolombo.tools.automaton.grpc.agent.MStage.getDefaultInstance()) return this;
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (!other.getDisplay().isEmpty()) {
        display_ = other.display_;
        onChanged();
      }
      if (!other.getCondition().isEmpty()) {
        condition_ = other.condition_;
        onChanged();
      }
      if (other.hasLoop()) {
        mergeLoop(other.getLoop());
      }
      if (other.hasForeach()) {
        mergeForeach(other.getForeach());
      }
      if (parametersBuilder_ == null) {
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
      } else {
        if (!other.parameters_.isEmpty()) {
          if (parametersBuilder_.isEmpty()) {
            parametersBuilder_.dispose();
            parametersBuilder_ = null;
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000020);
            parametersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getParametersFieldBuilder() : null;
          } else {
            parametersBuilder_.addAllMessages(other.parameters_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.francoiscolombo.tools.automaton.grpc.agent.MStage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.francoiscolombo.tools.automaton.grpc.agent.MStage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object action_ = "";
    /**
     * <code>string action = 1;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action = 1;</code>
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string action = 1;</code>
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>string action = 1;</code>
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object display_ = "";
    /**
     * <code>string display = 2;</code>
     */
    public java.lang.String getDisplay() {
      java.lang.Object ref = display_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        display_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string display = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayBytes() {
      java.lang.Object ref = display_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        display_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string display = 2;</code>
     */
    public Builder setDisplay(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      display_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string display = 2;</code>
     */
    public Builder clearDisplay() {
      
      display_ = getDefaultInstance().getDisplay();
      onChanged();
      return this;
    }
    /**
     * <code>string display = 2;</code>
     */
    public Builder setDisplayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      display_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object condition_ = "";
    /**
     * <code>string condition = 3;</code>
     */
    public java.lang.String getCondition() {
      java.lang.Object ref = condition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        condition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string condition = 3;</code>
     */
    public com.google.protobuf.ByteString
        getConditionBytes() {
      java.lang.Object ref = condition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        condition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string condition = 3;</code>
     */
    public Builder setCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      condition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 3;</code>
     */
    public Builder clearCondition() {
      
      condition_ = getDefaultInstance().getCondition();
      onChanged();
      return this;
    }
    /**
     * <code>string condition = 3;</code>
     */
    public Builder setConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      condition_ = value;
      onChanged();
      return this;
    }

    private net.francoiscolombo.tools.automaton.grpc.agent.MLoop loop_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MLoop, net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MLoopOrBuilder> loopBuilder_;
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public boolean hasLoop() {
      return loopBuilder_ != null || loop_ != null;
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MLoop getLoop() {
      if (loopBuilder_ == null) {
        return loop_ == null ? net.francoiscolombo.tools.automaton.grpc.agent.MLoop.getDefaultInstance() : loop_;
      } else {
        return loopBuilder_.getMessage();
      }
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public Builder setLoop(net.francoiscolombo.tools.automaton.grpc.agent.MLoop value) {
      if (loopBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loop_ = value;
        onChanged();
      } else {
        loopBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public Builder setLoop(
        net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder builderForValue) {
      if (loopBuilder_ == null) {
        loop_ = builderForValue.build();
        onChanged();
      } else {
        loopBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public Builder mergeLoop(net.francoiscolombo.tools.automaton.grpc.agent.MLoop value) {
      if (loopBuilder_ == null) {
        if (loop_ != null) {
          loop_ =
            net.francoiscolombo.tools.automaton.grpc.agent.MLoop.newBuilder(loop_).mergeFrom(value).buildPartial();
        } else {
          loop_ = value;
        }
        onChanged();
      } else {
        loopBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public Builder clearLoop() {
      if (loopBuilder_ == null) {
        loop_ = null;
        onChanged();
      } else {
        loop_ = null;
        loopBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder getLoopBuilder() {
      
      onChanged();
      return getLoopFieldBuilder().getBuilder();
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MLoopOrBuilder getLoopOrBuilder() {
      if (loopBuilder_ != null) {
        return loopBuilder_.getMessageOrBuilder();
      } else {
        return loop_ == null ?
            net.francoiscolombo.tools.automaton.grpc.agent.MLoop.getDefaultInstance() : loop_;
      }
    }
    /**
     * <code>.agent.MLoop loop = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MLoop, net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MLoopOrBuilder> 
        getLoopFieldBuilder() {
      if (loopBuilder_ == null) {
        loopBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.francoiscolombo.tools.automaton.grpc.agent.MLoop, net.francoiscolombo.tools.automaton.grpc.agent.MLoop.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MLoopOrBuilder>(
                getLoop(),
                getParentForChildren(),
                isClean());
        loop_ = null;
      }
      return loopBuilder_;
    }

    private net.francoiscolombo.tools.automaton.grpc.agent.MForEach foreach_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MForEach, net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MForEachOrBuilder> foreachBuilder_;
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public boolean hasForeach() {
      return foreachBuilder_ != null || foreach_ != null;
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MForEach getForeach() {
      if (foreachBuilder_ == null) {
        return foreach_ == null ? net.francoiscolombo.tools.automaton.grpc.agent.MForEach.getDefaultInstance() : foreach_;
      } else {
        return foreachBuilder_.getMessage();
      }
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public Builder setForeach(net.francoiscolombo.tools.automaton.grpc.agent.MForEach value) {
      if (foreachBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        foreach_ = value;
        onChanged();
      } else {
        foreachBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public Builder setForeach(
        net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder builderForValue) {
      if (foreachBuilder_ == null) {
        foreach_ = builderForValue.build();
        onChanged();
      } else {
        foreachBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public Builder mergeForeach(net.francoiscolombo.tools.automaton.grpc.agent.MForEach value) {
      if (foreachBuilder_ == null) {
        if (foreach_ != null) {
          foreach_ =
            net.francoiscolombo.tools.automaton.grpc.agent.MForEach.newBuilder(foreach_).mergeFrom(value).buildPartial();
        } else {
          foreach_ = value;
        }
        onChanged();
      } else {
        foreachBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public Builder clearForeach() {
      if (foreachBuilder_ == null) {
        foreach_ = null;
        onChanged();
      } else {
        foreach_ = null;
        foreachBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder getForeachBuilder() {
      
      onChanged();
      return getForeachFieldBuilder().getBuilder();
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MForEachOrBuilder getForeachOrBuilder() {
      if (foreachBuilder_ != null) {
        return foreachBuilder_.getMessageOrBuilder();
      } else {
        return foreach_ == null ?
            net.francoiscolombo.tools.automaton.grpc.agent.MForEach.getDefaultInstance() : foreach_;
      }
    }
    /**
     * <code>.agent.MForEach foreach = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MForEach, net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MForEachOrBuilder> 
        getForeachFieldBuilder() {
      if (foreachBuilder_ == null) {
        foreachBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            net.francoiscolombo.tools.automaton.grpc.agent.MForEach, net.francoiscolombo.tools.automaton.grpc.agent.MForEach.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MForEachOrBuilder>(
                getForeach(),
                getParentForChildren(),
                isClean());
        foreach_ = null;
      }
      return foreachBuilder_;
    }

    private java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MParameter> parameters_ =
      java.util.Collections.emptyList();
    private void ensureParametersIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        parameters_ = new java.util.ArrayList<net.francoiscolombo.tools.automaton.grpc.agent.MParameter>(parameters_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MParameter, net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder> parametersBuilder_;

    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MParameter> getParametersList() {
      if (parametersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parameters_);
      } else {
        return parametersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public int getParametersCount() {
      if (parametersBuilder_ == null) {
        return parameters_.size();
      } else {
        return parametersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MParameter getParameters(int index) {
      if (parametersBuilder_ == null) {
        return parameters_.get(index);
      } else {
        return parametersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder setParameters(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MParameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.set(index, value);
        onChanged();
      } else {
        parametersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder setParameters(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.set(index, builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder addParameters(net.francoiscolombo.tools.automaton.grpc.agent.MParameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
      } else {
        parametersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder addParameters(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MParameter value) {
      if (parametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParametersIsMutable();
        parameters_.add(index, value);
        onChanged();
      } else {
        parametersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder addParameters(
        net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.add(builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder addParameters(
        int index, net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder builderForValue) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.add(index, builderForValue.build());
        onChanged();
      } else {
        parametersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder addAllParameters(
        java.lang.Iterable<? extends net.francoiscolombo.tools.automaton.grpc.agent.MParameter> values) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameters_);
        onChanged();
      } else {
        parametersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder clearParameters() {
      if (parametersBuilder_ == null) {
        parameters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        parametersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public Builder removeParameters(int index) {
      if (parametersBuilder_ == null) {
        ensureParametersIsMutable();
        parameters_.remove(index);
        onChanged();
      } else {
        parametersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder getParametersBuilder(
        int index) {
      return getParametersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder getParametersOrBuilder(
        int index) {
      if (parametersBuilder_ == null) {
        return parameters_.get(index);  } else {
        return parametersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public java.util.List<? extends net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder> 
         getParametersOrBuilderList() {
      if (parametersBuilder_ != null) {
        return parametersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parameters_);
      }
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder addParametersBuilder() {
      return getParametersFieldBuilder().addBuilder(
          net.francoiscolombo.tools.automaton.grpc.agent.MParameter.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder addParametersBuilder(
        int index) {
      return getParametersFieldBuilder().addBuilder(
          index, net.francoiscolombo.tools.automaton.grpc.agent.MParameter.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.MParameter parameters = 6;</code>
     */
    public java.util.List<net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder> 
         getParametersBuilderList() {
      return getParametersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.francoiscolombo.tools.automaton.grpc.agent.MParameter, net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder> 
        getParametersFieldBuilder() {
      if (parametersBuilder_ == null) {
        parametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.francoiscolombo.tools.automaton.grpc.agent.MParameter, net.francoiscolombo.tools.automaton.grpc.agent.MParameter.Builder, net.francoiscolombo.tools.automaton.grpc.agent.MParameterOrBuilder>(
                parameters_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        parameters_ = null;
      }
      return parametersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:agent.MStage)
  }

  // @@protoc_insertion_point(class_scope:agent.MStage)
  private static final net.francoiscolombo.tools.automaton.grpc.agent.MStage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.francoiscolombo.tools.automaton.grpc.agent.MStage();
  }

  public static net.francoiscolombo.tools.automaton.grpc.agent.MStage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MStage>
      PARSER = new com.google.protobuf.AbstractParser<MStage>() {
    public MStage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new MStage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MStage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MStage> getParserForType() {
    return PARSER;
  }

  public net.francoiscolombo.tools.automaton.grpc.agent.MStage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

