// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package net.francoiscolombo.tools.automaton.grpc.agent;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MLoop_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MLoop_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MForEach_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MForEach_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MStage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MStage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MVariable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MVariable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MPlaybook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MPlaybook_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MPing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MPing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agent_MPong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agent_MPong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\005agent\"%\n\005MLoop\022\r\n\005index" +
      "\030\001 \001(\t\022\r\n\005range\030\002 \001(\r\"\031\n\010MForEach\022\r\n\005ite" +
      "ms\030\001 \003(\t\"+\n\nMParameter\022\r\n\005pname\030\001 \001(\t\022\016\n" +
      "\006pvalue\030\002 \001(\t\"\241\001\n\006MStage\022\016\n\006action\030\001 \001(\t" +
      "\022\017\n\007display\030\002 \001(\t\022\021\n\tcondition\030\003 \001(\t\022\032\n\004" +
      "loop\030\004 \001(\0132\014.agent.MLoop\022 \n\007foreach\030\005 \001(" +
      "\0132\017.agent.MForEach\022%\n\nparameters\030\006 \003(\0132\021" +
      ".agent.MParameter\"(\n\tMVariable\022\014\n\004name\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t\"]\n\tMPlaybook\022\014\n\004name" +
      "\030\001 \001(\t\022#\n\tvariables\030\002 \003(\0132\020.agent.MVaria",
      "ble\022\035\n\006stages\030\003 \003(\0132\r.agent.MStage\":\n\tMR" +
      "esponse\022\014\n\004code\030\001 \001(\r\022\016\n\006reason\030\002 \001(\t\022\017\n" +
      "\007message\030\003 \001(\t\"\025\n\005MPing\022\014\n\004ping\030\001 \001(\t\"\025\n" +
      "\005MPong\022\014\n\004pong\030\001 \001(\t2^\n\014AgentService\022*\n\004" +
      "play\022\020.agent.MPlaybook\032\020.agent.MResponse" +
      "\022\"\n\004ping\022\014.agent.MPing\032\014.agent.MPongB2\n." +
      "net.francoiscolombo.tools.automaton.grpc" +
      ".agentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_agent_MLoop_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agent_MLoop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MLoop_descriptor,
        new java.lang.String[] { "Index", "Range", });
    internal_static_agent_MForEach_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_agent_MForEach_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MForEach_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_agent_MParameter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_agent_MParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MParameter_descriptor,
        new java.lang.String[] { "Pname", "Pvalue", });
    internal_static_agent_MStage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_agent_MStage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MStage_descriptor,
        new java.lang.String[] { "Action", "Display", "Condition", "Loop", "Foreach", "Parameters", });
    internal_static_agent_MVariable_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_agent_MVariable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MVariable_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_agent_MPlaybook_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_agent_MPlaybook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MPlaybook_descriptor,
        new java.lang.String[] { "Name", "Variables", "Stages", });
    internal_static_agent_MResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_agent_MResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MResponse_descriptor,
        new java.lang.String[] { "Code", "Reason", "Message", });
    internal_static_agent_MPing_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_agent_MPing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MPing_descriptor,
        new java.lang.String[] { "Ping", });
    internal_static_agent_MPong_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_agent_MPong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agent_MPong_descriptor,
        new java.lang.String[] { "Pong", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
